FROM node:lts AS runtime
WORKDIR /app

COPY . .

RUN npm install -g npm@10.9.1
RUN npm install
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321

ARG SUPABASE_URL
ENV SUPABASE_URL=$SUPABASE_URL

ARG SUPABASE_ANON_KEY
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

ARG SUPABASE_SERVICE_ROLE_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY

EXPOSE 4321
CMD node ./dist/server/entry.mjs