FROM node:lts AS runtime
WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321

ARG SUPABASE_URL
ENV SUPABASE_URL=$SUPABASE_URL

ARG SUPABASE_ANON_KEY
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

ARG AUTHORIZED_IPS
ENV AUTHORIZED_IPS=$AUTHORIZED_IPS

EXPOSE 4321
CMD node ./dist/server/entry.mjs