
services:
  web:
    image: fuzion-website
    ports:
      - "4321:4321"
    environment:
      SUPABASE_URL: https://jbopupmzeqrmtvbpskgo.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impib3B1cG16ZXFybXR2YnBza2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE0NDYwMzgsImV4cCI6MjA0NzAyMjAzOH0.du1PEBaFoxMkIZK8dMtY8hp7tQ_Bjv3V3vOiQ7kSdWc
      AUTHORIZED_IPS: 127.0.0.1,0.0.0.0
